[package]
name = "snowman"
version = "0.1.0"
edition = "2018"

[dependencies]
futures-intrusive = "0.4.0"
http = "0.2.4"
hyper = { version = "0.14.10", features = ["server"] }
tokio = { version = "1.8.1", features = ["rt-multi-thread", "macros", "time"] }
